#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_opacity               off

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xfff07178
yabai -m config normal_window_border_color   0xff353535
yabai -m config insert_window_border_color   0xff212121
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config window_topmost on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   8

# Space labels
yabai -m space 1 --label "1"
yabai -m space 2 --label "2"
yabai -m space 3 --label "3"
yabai -m space 4 --label "4"
yabai -m space 5 --label "5"
yabai -m space 6 --label "6"
yabai -m space 7 --label "7"
yabai -m space 8 --label "8"
yabai -m space 9 --label "9"
yabai -m space 10 --label "10"


# Float
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=offecho "yabai configuration loaded.."
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off


echo "yabai configuration loaded.."
